[package]
name = "open-ai-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-extensions = { tag = "0.1.5", git = "https://github.com/MyJetTools/rust-extensions.git" }

serde = { version = "*", features = ["derive"] }
serde_json = "*"
open-ai-macros = { path = "../open-ai-macros" }
